### ISSUE TITLE
Protect users before linking accounts.

### ISSUE THREAD

**Issue by SylveonBottle** [DiscordSRV/RequireLinked4Gameplay#1]
When a user joins the server but hasn't linked their account, RequireLinked4Gameplay blocks movements.  
Unfortunately this is.. quite bad, considering a hostile mob or other players can kill them.

I'd like to suggest giving these users temporary godmode of some sort until they lock their account. 

This might be done just by giving the user invisibility (do hostile mobs see users with invisibility?), temporary godmode, placing them into spectator mode, not sending the player's packets, etc until they finally do link their accounts.

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/RequireLinked4Gameplay/commit/f136a6926ea4afb47099ce2f3c16a6b291929197 https://github.com/DiscordSRV/RequireLinked4Gameplay/releases/download/v1.1.0/RequireLinked4Gameplay.jar
